#!/bin/sh

set -eu

if [ "$1" = remove ]; then
    if [ -x /usr/bin/deb-systemd-helper ]; then
        deb-systemd-helper mask shallan.service >/dev/null || true
    fi
fi

if [ "$1" = purge ]; then
    if [ -x /usr/bin/deb-systemd-helper ]; then
        deb-systemd-helper purge shallan.service >/dev/null || true
        deb-systemd-helper unmask shallan.service >/dev/null || true
    fi
fi
